description: gan_mnist_pytorch_lightning_const
records_per_epoch: 55000
hyperparameters:
  global_batch_size: 64
  lr: 0.0002
  b1: 0.5
  b2: 0.999
searcher:
  name: single
  metric: loss
  max_length:
      epochs: 5
  smaller_is_better: true
entrypoint: model_def:GANTrial
environment:
  image: determinedai/environments:py-3.6.9-pytorch-1.7-lightning-1.2-tf-2.4-cpu-0.9.0
