description: mnist_pytorch_lightning_const
max_restarts: 1
hyperparameters:
  global_batch_size: 64
  learning_rate: 0.001
searcher:
  name: single
  metric: val_loss
  max_length:
      batches: 937
  smaller_is_better: true
entrypoint: model_def:MNISTTrial
